version: "3.9"

services:
  db:
    container_name: db
    restart: unless-stopped
    image: mysql:8.0-oracle
    profiles:
      - db
      - all
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 30s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      PGDATA: /data/mysql
    ports:
      - "3309:3306"
    networks:
      - weather-app
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
    image: weather-app:latest
    profiles:
      - app
      - all
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 2
      start_period: 20s
      timeout: 10s
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CHANGELOG_FILE=${CHANGELOG_FILE}
      - DB_JDBC_URL=${DB_JDBC_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - OWM_API_KEY=${OWM_API_KEY}
      - JAVA_OPTS=-Dorg.apache.catalina.startup.EXIT_ON_INIT_FAILURE=true
    ports:
      - "8090:8080"
    networks:
      - weather-app

networks:
  weather-app:
    driver: bridge